# Generated by Django 4.1.3 on 2022-11-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("zodiac", models.CharField(max_length=20)),
                ("height", models.CharField(max_length=10)),
                ("weight", models.CharField(max_length=10)),
            ],
        ),
    ]
