# Generated by Django 4.1.3 on 2022-12-02 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0002_player_photos"),
    ]

    operations = [
        migrations.AlterModelTable(name="player", table="player",),
    ]
