# Generated by Django 4.1.3 on 2022-12-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("info", models.TextField()),
                ("photos", models.CharField(max_length=200)),
                ("links", models.CharField(max_length=200)),
                ("create_date", models.DateField(auto_now_add=True)),
            ],
            options={"db_table": "news",},
        ),
    ]
