# Generated by Django 4.1.3 on 2022-12-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="photo", field=models.CharField(max_length=255),
        ),
    ]
